<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class MainForm
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(MainForm))
        Dim BorderEdges1 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges2 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges3 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges4 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges5 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges6 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges7 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges8 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges9 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges10 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges11 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Me.BunifuPanel1 = New Bunifu.UI.WinForms.BunifuPanel()
        Me.Officials_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.Archive_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.Logout_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.Settings_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.Activities_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.Dashboard_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.BunifuLabel1 = New Bunifu.UI.WinForms.BunifuLabel()
        Me.Residents_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.Purok_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.Clearance_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.Record_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.Blotter_Button = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.MainPanel = New Bunifu.UI.WinForms.BunifuPanel()
        Me.BunifuPanel1.SuspendLayout()
        Me.SuspendLayout()
        '
        'BunifuPanel1
        '
        Me.BunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent
        Me.BunifuPanel1.BackgroundImage = CType(resources.GetObject("BunifuPanel1.BackgroundImage"), System.Drawing.Image)
        Me.BunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch
        Me.BunifuPanel1.BorderColor = System.Drawing.Color.Transparent
        Me.BunifuPanel1.BorderRadius = 3
        Me.BunifuPanel1.BorderThickness = 1
        Me.BunifuPanel1.Controls.Add(Me.Officials_Button)
        Me.BunifuPanel1.Controls.Add(Me.Archive_Button)
        Me.BunifuPanel1.Controls.Add(Me.Logout_Button)
        Me.BunifuPanel1.Controls.Add(Me.Settings_Button)
        Me.BunifuPanel1.Controls.Add(Me.Activities_Button)
        Me.BunifuPanel1.Controls.Add(Me.Dashboard_Button)
        Me.BunifuPanel1.Controls.Add(Me.BunifuLabel1)
        Me.BunifuPanel1.Controls.Add(Me.Residents_Button)
        Me.BunifuPanel1.Controls.Add(Me.Purok_Button)
        Me.BunifuPanel1.Controls.Add(Me.Clearance_Button)
        Me.BunifuPanel1.Controls.Add(Me.Record_Button)
        Me.BunifuPanel1.Controls.Add(Me.Blotter_Button)
        Me.BunifuPanel1.Location = New System.Drawing.Point(-1, -1)
        Me.BunifuPanel1.Name = "BunifuPanel1"
        Me.BunifuPanel1.ShowBorders = True
        Me.BunifuPanel1.Size = New System.Drawing.Size(245, 728)
        Me.BunifuPanel1.TabIndex = 0
        '
        'Officials_Button
        '
        Me.Officials_Button.AllowAnimations = True
        Me.Officials_Button.AllowMouseEffects = True
        Me.Officials_Button.AllowToggling = False
        Me.Officials_Button.AnimationSpeed = 200
        Me.Officials_Button.AutoGenerateColors = False
        Me.Officials_Button.AutoRoundBorders = False
        Me.Officials_Button.AutoSizeLeftIcon = True
        Me.Officials_Button.AutoSizeRightIcon = True
        Me.Officials_Button.BackColor = System.Drawing.Color.Transparent
        Me.Officials_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Officials_Button.BackgroundImage = CType(resources.GetObject("Officials_Button.BackgroundImage"), System.Drawing.Image)
        Me.Officials_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Officials_Button.ButtonText = "OFFICIALS"
        Me.Officials_Button.ButtonTextMarginLeft = 0
        Me.Officials_Button.ColorContrastOnClick = 45
        Me.Officials_Button.ColorContrastOnHover = 45
        Me.Officials_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges1.BottomLeft = True
        BorderEdges1.BottomRight = True
        BorderEdges1.TopLeft = True
        BorderEdges1.TopRight = True
        Me.Officials_Button.CustomizableEdges = BorderEdges1
        Me.Officials_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Officials_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Officials_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Officials_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Officials_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Officials_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Officials_Button.ForeColor = System.Drawing.Color.White
        Me.Officials_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Officials_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Officials_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Officials_Button.IconMarginLeft = 11
        Me.Officials_Button.IconPadding = 10
        Me.Officials_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Officials_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Officials_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Officials_Button.IconSize = 25
        Me.Officials_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Officials_Button.IdleBorderRadius = 1
        Me.Officials_Button.IdleBorderThickness = 1
        Me.Officials_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Officials_Button.IdleIconLeftImage = Nothing
        Me.Officials_Button.IdleIconRightImage = Nothing
        Me.Officials_Button.IndicateFocus = False
        Me.Officials_Button.Location = New System.Drawing.Point(0, 229)
        Me.Officials_Button.Name = "Officials_Button"
        Me.Officials_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Officials_Button.OnDisabledState.BorderRadius = 1
        Me.Officials_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Officials_Button.OnDisabledState.BorderThickness = 1
        Me.Officials_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Officials_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Officials_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Officials_Button.OnDisabledState.IconRightImage = Nothing
        Me.Officials_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Officials_Button.onHoverState.BorderRadius = 1
        Me.Officials_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Officials_Button.onHoverState.BorderThickness = 1
        Me.Officials_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Officials_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Officials_Button.onHoverState.IconLeftImage = Nothing
        Me.Officials_Button.onHoverState.IconRightImage = Nothing
        Me.Officials_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Officials_Button.OnIdleState.BorderRadius = 1
        Me.Officials_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Officials_Button.OnIdleState.BorderThickness = 1
        Me.Officials_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Officials_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Officials_Button.OnIdleState.IconLeftImage = Nothing
        Me.Officials_Button.OnIdleState.IconRightImage = Nothing
        Me.Officials_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Officials_Button.OnPressedState.BorderRadius = 1
        Me.Officials_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Officials_Button.OnPressedState.BorderThickness = 1
        Me.Officials_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Officials_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Officials_Button.OnPressedState.IconLeftImage = Nothing
        Me.Officials_Button.OnPressedState.IconRightImage = Nothing
        Me.Officials_Button.Size = New System.Drawing.Size(245, 55)
        Me.Officials_Button.TabIndex = 5
        Me.Officials_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Officials_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Officials_Button.TextMarginLeft = 0
        Me.Officials_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Officials_Button.UseDefaultRadiusAndThickness = True
        '
        'Archive_Button
        '
        Me.Archive_Button.AllowAnimations = True
        Me.Archive_Button.AllowMouseEffects = True
        Me.Archive_Button.AllowToggling = False
        Me.Archive_Button.AnimationSpeed = 200
        Me.Archive_Button.AutoGenerateColors = False
        Me.Archive_Button.AutoRoundBorders = False
        Me.Archive_Button.AutoSizeLeftIcon = True
        Me.Archive_Button.AutoSizeRightIcon = True
        Me.Archive_Button.BackColor = System.Drawing.Color.Transparent
        Me.Archive_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Archive_Button.BackgroundImage = CType(resources.GetObject("Archive_Button.BackgroundImage"), System.Drawing.Image)
        Me.Archive_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Archive_Button.ButtonText = "ARCHIVE"
        Me.Archive_Button.ButtonTextMarginLeft = 0
        Me.Archive_Button.ColorContrastOnClick = 45
        Me.Archive_Button.ColorContrastOnHover = 45
        Me.Archive_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges2.BottomLeft = True
        BorderEdges2.BottomRight = True
        BorderEdges2.TopLeft = True
        BorderEdges2.TopRight = True
        Me.Archive_Button.CustomizableEdges = BorderEdges2
        Me.Archive_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Archive_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Archive_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Archive_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Archive_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Archive_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Archive_Button.ForeColor = System.Drawing.Color.White
        Me.Archive_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Archive_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Archive_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Archive_Button.IconMarginLeft = 11
        Me.Archive_Button.IconPadding = 10
        Me.Archive_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Archive_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Archive_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Archive_Button.IconSize = 25
        Me.Archive_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Archive_Button.IdleBorderRadius = 1
        Me.Archive_Button.IdleBorderThickness = 1
        Me.Archive_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Archive_Button.IdleIconLeftImage = Nothing
        Me.Archive_Button.IdleIconRightImage = Nothing
        Me.Archive_Button.IndicateFocus = False
        Me.Archive_Button.Location = New System.Drawing.Point(0, 469)
        Me.Archive_Button.Name = "Archive_Button"
        Me.Archive_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Archive_Button.OnDisabledState.BorderRadius = 1
        Me.Archive_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Archive_Button.OnDisabledState.BorderThickness = 1
        Me.Archive_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Archive_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Archive_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Archive_Button.OnDisabledState.IconRightImage = Nothing
        Me.Archive_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Archive_Button.onHoverState.BorderRadius = 1
        Me.Archive_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Archive_Button.onHoverState.BorderThickness = 1
        Me.Archive_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Archive_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Archive_Button.onHoverState.IconLeftImage = Nothing
        Me.Archive_Button.onHoverState.IconRightImage = Nothing
        Me.Archive_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Archive_Button.OnIdleState.BorderRadius = 1
        Me.Archive_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Archive_Button.OnIdleState.BorderThickness = 1
        Me.Archive_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Archive_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Archive_Button.OnIdleState.IconLeftImage = Nothing
        Me.Archive_Button.OnIdleState.IconRightImage = Nothing
        Me.Archive_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Archive_Button.OnPressedState.BorderRadius = 1
        Me.Archive_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Archive_Button.OnPressedState.BorderThickness = 1
        Me.Archive_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Archive_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Archive_Button.OnPressedState.IconLeftImage = Nothing
        Me.Archive_Button.OnPressedState.IconRightImage = Nothing
        Me.Archive_Button.Size = New System.Drawing.Size(245, 55)
        Me.Archive_Button.TabIndex = 11
        Me.Archive_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Archive_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Archive_Button.TextMarginLeft = 0
        Me.Archive_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Archive_Button.UseDefaultRadiusAndThickness = True
        '
        'Logout_Button
        '
        Me.Logout_Button.AllowAnimations = True
        Me.Logout_Button.AllowMouseEffects = True
        Me.Logout_Button.AllowToggling = False
        Me.Logout_Button.AnimationSpeed = 200
        Me.Logout_Button.AutoGenerateColors = False
        Me.Logout_Button.AutoRoundBorders = False
        Me.Logout_Button.AutoSizeLeftIcon = True
        Me.Logout_Button.AutoSizeRightIcon = True
        Me.Logout_Button.BackColor = System.Drawing.Color.Transparent
        Me.Logout_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Logout_Button.BackgroundImage = CType(resources.GetObject("Logout_Button.BackgroundImage"), System.Drawing.Image)
        Me.Logout_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Logout_Button.ButtonText = "LOGOUT"
        Me.Logout_Button.ButtonTextMarginLeft = 0
        Me.Logout_Button.ColorContrastOnClick = 45
        Me.Logout_Button.ColorContrastOnHover = 45
        Me.Logout_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges3.BottomLeft = True
        BorderEdges3.BottomRight = True
        BorderEdges3.TopLeft = True
        BorderEdges3.TopRight = True
        Me.Logout_Button.CustomizableEdges = BorderEdges3
        Me.Logout_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Logout_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Logout_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Logout_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Logout_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Logout_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Logout_Button.ForeColor = System.Drawing.Color.White
        Me.Logout_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Logout_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Logout_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Logout_Button.IconMarginLeft = 11
        Me.Logout_Button.IconPadding = 10
        Me.Logout_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Logout_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Logout_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Logout_Button.IconSize = 25
        Me.Logout_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Logout_Button.IdleBorderRadius = 1
        Me.Logout_Button.IdleBorderThickness = 1
        Me.Logout_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Logout_Button.IdleIconLeftImage = Nothing
        Me.Logout_Button.IdleIconRightImage = Nothing
        Me.Logout_Button.IndicateFocus = False
        Me.Logout_Button.Location = New System.Drawing.Point(1, 649)
        Me.Logout_Button.Name = "Logout_Button"
        Me.Logout_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Logout_Button.OnDisabledState.BorderRadius = 1
        Me.Logout_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Logout_Button.OnDisabledState.BorderThickness = 1
        Me.Logout_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Logout_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Logout_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Logout_Button.OnDisabledState.IconRightImage = Nothing
        Me.Logout_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Logout_Button.onHoverState.BorderRadius = 1
        Me.Logout_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Logout_Button.onHoverState.BorderThickness = 1
        Me.Logout_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Logout_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Logout_Button.onHoverState.IconLeftImage = Nothing
        Me.Logout_Button.onHoverState.IconRightImage = Nothing
        Me.Logout_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Logout_Button.OnIdleState.BorderRadius = 1
        Me.Logout_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Logout_Button.OnIdleState.BorderThickness = 1
        Me.Logout_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Logout_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Logout_Button.OnIdleState.IconLeftImage = Nothing
        Me.Logout_Button.OnIdleState.IconRightImage = Nothing
        Me.Logout_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Logout_Button.OnPressedState.BorderRadius = 1
        Me.Logout_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Logout_Button.OnPressedState.BorderThickness = 1
        Me.Logout_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Logout_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Logout_Button.OnPressedState.IconLeftImage = Nothing
        Me.Logout_Button.OnPressedState.IconRightImage = Nothing
        Me.Logout_Button.Size = New System.Drawing.Size(245, 55)
        Me.Logout_Button.TabIndex = 8
        Me.Logout_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Logout_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Logout_Button.TextMarginLeft = 0
        Me.Logout_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Logout_Button.UseDefaultRadiusAndThickness = True
        '
        'Settings_Button
        '
        Me.Settings_Button.AllowAnimations = True
        Me.Settings_Button.AllowMouseEffects = True
        Me.Settings_Button.AllowToggling = False
        Me.Settings_Button.AnimationSpeed = 200
        Me.Settings_Button.AutoGenerateColors = False
        Me.Settings_Button.AutoRoundBorders = False
        Me.Settings_Button.AutoSizeLeftIcon = True
        Me.Settings_Button.AutoSizeRightIcon = True
        Me.Settings_Button.BackColor = System.Drawing.Color.Transparent
        Me.Settings_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Settings_Button.BackgroundImage = CType(resources.GetObject("Settings_Button.BackgroundImage"), System.Drawing.Image)
        Me.Settings_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Settings_Button.ButtonText = "SETTINGS"
        Me.Settings_Button.ButtonTextMarginLeft = 0
        Me.Settings_Button.ColorContrastOnClick = 45
        Me.Settings_Button.ColorContrastOnHover = 45
        Me.Settings_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges4.BottomLeft = True
        BorderEdges4.BottomRight = True
        BorderEdges4.TopLeft = True
        BorderEdges4.TopRight = True
        Me.Settings_Button.CustomizableEdges = BorderEdges4
        Me.Settings_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Settings_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Settings_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Settings_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Settings_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Settings_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Settings_Button.ForeColor = System.Drawing.Color.White
        Me.Settings_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Settings_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Settings_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Settings_Button.IconMarginLeft = 11
        Me.Settings_Button.IconPadding = 10
        Me.Settings_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Settings_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Settings_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Settings_Button.IconSize = 25
        Me.Settings_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Settings_Button.IdleBorderRadius = 1
        Me.Settings_Button.IdleBorderThickness = 1
        Me.Settings_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Settings_Button.IdleIconLeftImage = Nothing
        Me.Settings_Button.IdleIconRightImage = Nothing
        Me.Settings_Button.IndicateFocus = False
        Me.Settings_Button.Location = New System.Drawing.Point(1, 529)
        Me.Settings_Button.Name = "Settings_Button"
        Me.Settings_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Settings_Button.OnDisabledState.BorderRadius = 1
        Me.Settings_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Settings_Button.OnDisabledState.BorderThickness = 1
        Me.Settings_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Settings_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Settings_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Settings_Button.OnDisabledState.IconRightImage = Nothing
        Me.Settings_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Settings_Button.onHoverState.BorderRadius = 1
        Me.Settings_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Settings_Button.onHoverState.BorderThickness = 1
        Me.Settings_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Settings_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Settings_Button.onHoverState.IconLeftImage = Nothing
        Me.Settings_Button.onHoverState.IconRightImage = Nothing
        Me.Settings_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Settings_Button.OnIdleState.BorderRadius = 1
        Me.Settings_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Settings_Button.OnIdleState.BorderThickness = 1
        Me.Settings_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Settings_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Settings_Button.OnIdleState.IconLeftImage = Nothing
        Me.Settings_Button.OnIdleState.IconRightImage = Nothing
        Me.Settings_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Settings_Button.OnPressedState.BorderRadius = 1
        Me.Settings_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Settings_Button.OnPressedState.BorderThickness = 1
        Me.Settings_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Settings_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Settings_Button.OnPressedState.IconLeftImage = Nothing
        Me.Settings_Button.OnPressedState.IconRightImage = Nothing
        Me.Settings_Button.Size = New System.Drawing.Size(245, 55)
        Me.Settings_Button.TabIndex = 10
        Me.Settings_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Settings_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Settings_Button.TextMarginLeft = 0
        Me.Settings_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Settings_Button.UseDefaultRadiusAndThickness = True
        '
        'Activities_Button
        '
        Me.Activities_Button.AllowAnimations = True
        Me.Activities_Button.AllowMouseEffects = True
        Me.Activities_Button.AllowToggling = False
        Me.Activities_Button.AnimationSpeed = 200
        Me.Activities_Button.AutoGenerateColors = False
        Me.Activities_Button.AutoRoundBorders = False
        Me.Activities_Button.AutoSizeLeftIcon = True
        Me.Activities_Button.AutoSizeRightIcon = True
        Me.Activities_Button.BackColor = System.Drawing.Color.Transparent
        Me.Activities_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Activities_Button.BackgroundImage = CType(resources.GetObject("Activities_Button.BackgroundImage"), System.Drawing.Image)
        Me.Activities_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Activities_Button.ButtonText = "ACTIVITIES"
        Me.Activities_Button.ButtonTextMarginLeft = 0
        Me.Activities_Button.ColorContrastOnClick = 45
        Me.Activities_Button.ColorContrastOnHover = 45
        Me.Activities_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges5.BottomLeft = True
        BorderEdges5.BottomRight = True
        BorderEdges5.TopLeft = True
        BorderEdges5.TopRight = True
        Me.Activities_Button.CustomizableEdges = BorderEdges5
        Me.Activities_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Activities_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Activities_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Activities_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Activities_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Activities_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Activities_Button.ForeColor = System.Drawing.Color.White
        Me.Activities_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Activities_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Activities_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Activities_Button.IconMarginLeft = 11
        Me.Activities_Button.IconPadding = 10
        Me.Activities_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Activities_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Activities_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Activities_Button.IconSize = 25
        Me.Activities_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Activities_Button.IdleBorderRadius = 1
        Me.Activities_Button.IdleBorderThickness = 1
        Me.Activities_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Activities_Button.IdleIconLeftImage = Nothing
        Me.Activities_Button.IdleIconRightImage = Nothing
        Me.Activities_Button.IndicateFocus = False
        Me.Activities_Button.Location = New System.Drawing.Point(1, 589)
        Me.Activities_Button.Name = "Activities_Button"
        Me.Activities_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Activities_Button.OnDisabledState.BorderRadius = 1
        Me.Activities_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Activities_Button.OnDisabledState.BorderThickness = 1
        Me.Activities_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Activities_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Activities_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Activities_Button.OnDisabledState.IconRightImage = Nothing
        Me.Activities_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Activities_Button.onHoverState.BorderRadius = 1
        Me.Activities_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Activities_Button.onHoverState.BorderThickness = 1
        Me.Activities_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Activities_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Activities_Button.onHoverState.IconLeftImage = Nothing
        Me.Activities_Button.onHoverState.IconRightImage = Nothing
        Me.Activities_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Activities_Button.OnIdleState.BorderRadius = 1
        Me.Activities_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Activities_Button.OnIdleState.BorderThickness = 1
        Me.Activities_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Activities_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Activities_Button.OnIdleState.IconLeftImage = Nothing
        Me.Activities_Button.OnIdleState.IconRightImage = Nothing
        Me.Activities_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Activities_Button.OnPressedState.BorderRadius = 1
        Me.Activities_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Activities_Button.OnPressedState.BorderThickness = 1
        Me.Activities_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Activities_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Activities_Button.OnPressedState.IconLeftImage = Nothing
        Me.Activities_Button.OnPressedState.IconRightImage = Nothing
        Me.Activities_Button.Size = New System.Drawing.Size(245, 55)
        Me.Activities_Button.TabIndex = 9
        Me.Activities_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Activities_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Activities_Button.TextMarginLeft = 0
        Me.Activities_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Activities_Button.UseDefaultRadiusAndThickness = True
        '
        'Dashboard_Button
        '
        Me.Dashboard_Button.AllowAnimations = True
        Me.Dashboard_Button.AllowMouseEffects = True
        Me.Dashboard_Button.AllowToggling = False
        Me.Dashboard_Button.AnimationSpeed = 200
        Me.Dashboard_Button.AutoGenerateColors = False
        Me.Dashboard_Button.AutoRoundBorders = False
        Me.Dashboard_Button.AutoSizeLeftIcon = True
        Me.Dashboard_Button.AutoSizeRightIcon = True
        Me.Dashboard_Button.BackColor = System.Drawing.Color.Transparent
        Me.Dashboard_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Dashboard_Button.BackgroundImage = CType(resources.GetObject("Dashboard_Button.BackgroundImage"), System.Drawing.Image)
        Me.Dashboard_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Dashboard_Button.ButtonText = "DASHBOARD"
        Me.Dashboard_Button.ButtonTextMarginLeft = 0
        Me.Dashboard_Button.ColorContrastOnClick = 45
        Me.Dashboard_Button.ColorContrastOnHover = 45
        Me.Dashboard_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges6.BottomLeft = True
        BorderEdges6.BottomRight = True
        BorderEdges6.TopLeft = True
        BorderEdges6.TopRight = True
        Me.Dashboard_Button.CustomizableEdges = BorderEdges6
        Me.Dashboard_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Dashboard_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Dashboard_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Dashboard_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Dashboard_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Dashboard_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Dashboard_Button.ForeColor = System.Drawing.Color.White
        Me.Dashboard_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Dashboard_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Dashboard_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Dashboard_Button.IconMarginLeft = 11
        Me.Dashboard_Button.IconPadding = 10
        Me.Dashboard_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Dashboard_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Dashboard_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Dashboard_Button.IconSize = 25
        Me.Dashboard_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Dashboard_Button.IdleBorderRadius = 1
        Me.Dashboard_Button.IdleBorderThickness = 1
        Me.Dashboard_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Dashboard_Button.IdleIconLeftImage = Nothing
        Me.Dashboard_Button.IdleIconRightImage = Nothing
        Me.Dashboard_Button.IndicateFocus = False
        Me.Dashboard_Button.Location = New System.Drawing.Point(0, 52)
        Me.Dashboard_Button.Name = "Dashboard_Button"
        Me.Dashboard_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Dashboard_Button.OnDisabledState.BorderRadius = 1
        Me.Dashboard_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Dashboard_Button.OnDisabledState.BorderThickness = 1
        Me.Dashboard_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Dashboard_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Dashboard_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Dashboard_Button.OnDisabledState.IconRightImage = Nothing
        Me.Dashboard_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Dashboard_Button.onHoverState.BorderRadius = 1
        Me.Dashboard_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Dashboard_Button.onHoverState.BorderThickness = 1
        Me.Dashboard_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Dashboard_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Dashboard_Button.onHoverState.IconLeftImage = Nothing
        Me.Dashboard_Button.onHoverState.IconRightImage = Nothing
        Me.Dashboard_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Dashboard_Button.OnIdleState.BorderRadius = 1
        Me.Dashboard_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Dashboard_Button.OnIdleState.BorderThickness = 1
        Me.Dashboard_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Dashboard_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Dashboard_Button.OnIdleState.IconLeftImage = Nothing
        Me.Dashboard_Button.OnIdleState.IconRightImage = Nothing
        Me.Dashboard_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Dashboard_Button.OnPressedState.BorderRadius = 1
        Me.Dashboard_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Dashboard_Button.OnPressedState.BorderThickness = 1
        Me.Dashboard_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Dashboard_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Dashboard_Button.OnPressedState.IconLeftImage = Nothing
        Me.Dashboard_Button.OnPressedState.IconRightImage = Nothing
        Me.Dashboard_Button.Size = New System.Drawing.Size(245, 55)
        Me.Dashboard_Button.TabIndex = 1
        Me.Dashboard_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Dashboard_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Dashboard_Button.TextMarginLeft = 0
        Me.Dashboard_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Dashboard_Button.UseDefaultRadiusAndThickness = True
        '
        'BunifuLabel1
        '
        Me.BunifuLabel1.AllowParentOverrides = False
        Me.BunifuLabel1.AutoEllipsis = False
        Me.BunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default
        Me.BunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default
        Me.BunifuLabel1.Font = New System.Drawing.Font("Times New Roman", 24.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.BunifuLabel1.Location = New System.Drawing.Point(13, 3)
        Me.BunifuLabel1.Name = "BunifuLabel1"
        Me.BunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No
        Me.BunifuLabel1.Size = New System.Drawing.Size(217, 36)
        Me.BunifuLabel1.TabIndex = 0
        Me.BunifuLabel1.Text = "Barangay System"
        Me.BunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft
        Me.BunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.[Default]
        '
        'Residents_Button
        '
        Me.Residents_Button.AllowAnimations = True
        Me.Residents_Button.AllowMouseEffects = True
        Me.Residents_Button.AllowToggling = False
        Me.Residents_Button.AnimationSpeed = 200
        Me.Residents_Button.AutoGenerateColors = False
        Me.Residents_Button.AutoRoundBorders = False
        Me.Residents_Button.AutoSizeLeftIcon = True
        Me.Residents_Button.AutoSizeRightIcon = True
        Me.Residents_Button.BackColor = System.Drawing.Color.Transparent
        Me.Residents_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Residents_Button.BackgroundImage = CType(resources.GetObject("Residents_Button.BackgroundImage"), System.Drawing.Image)
        Me.Residents_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Residents_Button.ButtonText = "RESIDENTS"
        Me.Residents_Button.ButtonTextMarginLeft = 0
        Me.Residents_Button.ColorContrastOnClick = 45
        Me.Residents_Button.ColorContrastOnHover = 45
        Me.Residents_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges7.BottomLeft = True
        BorderEdges7.BottomRight = True
        BorderEdges7.TopLeft = True
        BorderEdges7.TopRight = True
        Me.Residents_Button.CustomizableEdges = BorderEdges7
        Me.Residents_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Residents_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Residents_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Residents_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Residents_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Residents_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Residents_Button.ForeColor = System.Drawing.Color.White
        Me.Residents_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Residents_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Residents_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Residents_Button.IconMarginLeft = 11
        Me.Residents_Button.IconPadding = 10
        Me.Residents_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Residents_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Residents_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Residents_Button.IconSize = 25
        Me.Residents_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Residents_Button.IdleBorderRadius = 1
        Me.Residents_Button.IdleBorderThickness = 1
        Me.Residents_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Residents_Button.IdleIconLeftImage = Nothing
        Me.Residents_Button.IdleIconRightImage = Nothing
        Me.Residents_Button.IndicateFocus = False
        Me.Residents_Button.Location = New System.Drawing.Point(0, 111)
        Me.Residents_Button.Name = "Residents_Button"
        Me.Residents_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Residents_Button.OnDisabledState.BorderRadius = 1
        Me.Residents_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Residents_Button.OnDisabledState.BorderThickness = 1
        Me.Residents_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Residents_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Residents_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Residents_Button.OnDisabledState.IconRightImage = Nothing
        Me.Residents_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Residents_Button.onHoverState.BorderRadius = 1
        Me.Residents_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Residents_Button.onHoverState.BorderThickness = 1
        Me.Residents_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Residents_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Residents_Button.onHoverState.IconLeftImage = Nothing
        Me.Residents_Button.onHoverState.IconRightImage = Nothing
        Me.Residents_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Residents_Button.OnIdleState.BorderRadius = 1
        Me.Residents_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Residents_Button.OnIdleState.BorderThickness = 1
        Me.Residents_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Residents_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Residents_Button.OnIdleState.IconLeftImage = Nothing
        Me.Residents_Button.OnIdleState.IconRightImage = Nothing
        Me.Residents_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Residents_Button.OnPressedState.BorderRadius = 1
        Me.Residents_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Residents_Button.OnPressedState.BorderThickness = 1
        Me.Residents_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Residents_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Residents_Button.OnPressedState.IconLeftImage = Nothing
        Me.Residents_Button.OnPressedState.IconRightImage = Nothing
        Me.Residents_Button.Size = New System.Drawing.Size(245, 55)
        Me.Residents_Button.TabIndex = 2
        Me.Residents_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Residents_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Residents_Button.TextMarginLeft = 0
        Me.Residents_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Residents_Button.UseDefaultRadiusAndThickness = True
        '
        'Purok_Button
        '
        Me.Purok_Button.AllowAnimations = True
        Me.Purok_Button.AllowMouseEffects = True
        Me.Purok_Button.AllowToggling = False
        Me.Purok_Button.AnimationSpeed = 200
        Me.Purok_Button.AutoGenerateColors = False
        Me.Purok_Button.AutoRoundBorders = False
        Me.Purok_Button.AutoSizeLeftIcon = True
        Me.Purok_Button.AutoSizeRightIcon = True
        Me.Purok_Button.BackColor = System.Drawing.Color.Transparent
        Me.Purok_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Purok_Button.BackgroundImage = CType(resources.GetObject("Purok_Button.BackgroundImage"), System.Drawing.Image)
        Me.Purok_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Purok_Button.ButtonText = "PUROK"
        Me.Purok_Button.ButtonTextMarginLeft = 0
        Me.Purok_Button.ColorContrastOnClick = 45
        Me.Purok_Button.ColorContrastOnHover = 45
        Me.Purok_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges8.BottomLeft = True
        BorderEdges8.BottomRight = True
        BorderEdges8.TopLeft = True
        BorderEdges8.TopRight = True
        Me.Purok_Button.CustomizableEdges = BorderEdges8
        Me.Purok_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Purok_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Purok_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Purok_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Purok_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Purok_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Purok_Button.ForeColor = System.Drawing.Color.White
        Me.Purok_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Purok_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Purok_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Purok_Button.IconMarginLeft = 11
        Me.Purok_Button.IconPadding = 10
        Me.Purok_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Purok_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Purok_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Purok_Button.IconSize = 25
        Me.Purok_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Purok_Button.IdleBorderRadius = 1
        Me.Purok_Button.IdleBorderThickness = 1
        Me.Purok_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Purok_Button.IdleIconLeftImage = Nothing
        Me.Purok_Button.IdleIconRightImage = Nothing
        Me.Purok_Button.IndicateFocus = False
        Me.Purok_Button.Location = New System.Drawing.Point(-1, 170)
        Me.Purok_Button.Name = "Purok_Button"
        Me.Purok_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Purok_Button.OnDisabledState.BorderRadius = 1
        Me.Purok_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Purok_Button.OnDisabledState.BorderThickness = 1
        Me.Purok_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Purok_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Purok_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Purok_Button.OnDisabledState.IconRightImage = Nothing
        Me.Purok_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Purok_Button.onHoverState.BorderRadius = 1
        Me.Purok_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Purok_Button.onHoverState.BorderThickness = 1
        Me.Purok_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Purok_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Purok_Button.onHoverState.IconLeftImage = Nothing
        Me.Purok_Button.onHoverState.IconRightImage = Nothing
        Me.Purok_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Purok_Button.OnIdleState.BorderRadius = 1
        Me.Purok_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Purok_Button.OnIdleState.BorderThickness = 1
        Me.Purok_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Purok_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Purok_Button.OnIdleState.IconLeftImage = Nothing
        Me.Purok_Button.OnIdleState.IconRightImage = Nothing
        Me.Purok_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Purok_Button.OnPressedState.BorderRadius = 1
        Me.Purok_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Purok_Button.OnPressedState.BorderThickness = 1
        Me.Purok_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Purok_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Purok_Button.OnPressedState.IconLeftImage = Nothing
        Me.Purok_Button.OnPressedState.IconRightImage = Nothing
        Me.Purok_Button.Size = New System.Drawing.Size(245, 55)
        Me.Purok_Button.TabIndex = 3
        Me.Purok_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Purok_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Purok_Button.TextMarginLeft = 0
        Me.Purok_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Purok_Button.UseDefaultRadiusAndThickness = True
        '
        'Clearance_Button
        '
        Me.Clearance_Button.AllowAnimations = True
        Me.Clearance_Button.AllowMouseEffects = True
        Me.Clearance_Button.AllowToggling = False
        Me.Clearance_Button.AnimationSpeed = 200
        Me.Clearance_Button.AutoGenerateColors = False
        Me.Clearance_Button.AutoRoundBorders = False
        Me.Clearance_Button.AutoSizeLeftIcon = True
        Me.Clearance_Button.AutoSizeRightIcon = True
        Me.Clearance_Button.BackColor = System.Drawing.Color.Transparent
        Me.Clearance_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Clearance_Button.BackgroundImage = CType(resources.GetObject("Clearance_Button.BackgroundImage"), System.Drawing.Image)
        Me.Clearance_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Clearance_Button.ButtonText = "CLEARANCE"
        Me.Clearance_Button.ButtonTextMarginLeft = 0
        Me.Clearance_Button.ColorContrastOnClick = 45
        Me.Clearance_Button.ColorContrastOnHover = 45
        Me.Clearance_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges9.BottomLeft = True
        BorderEdges9.BottomRight = True
        BorderEdges9.TopLeft = True
        BorderEdges9.TopRight = True
        Me.Clearance_Button.CustomizableEdges = BorderEdges9
        Me.Clearance_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Clearance_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Clearance_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Clearance_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Clearance_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Clearance_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Clearance_Button.ForeColor = System.Drawing.Color.White
        Me.Clearance_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Clearance_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Clearance_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Clearance_Button.IconMarginLeft = 11
        Me.Clearance_Button.IconPadding = 10
        Me.Clearance_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Clearance_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Clearance_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Clearance_Button.IconSize = 25
        Me.Clearance_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Clearance_Button.IdleBorderRadius = 1
        Me.Clearance_Button.IdleBorderThickness = 1
        Me.Clearance_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Clearance_Button.IdleIconLeftImage = Nothing
        Me.Clearance_Button.IdleIconRightImage = Nothing
        Me.Clearance_Button.IndicateFocus = False
        Me.Clearance_Button.Location = New System.Drawing.Point(0, 289)
        Me.Clearance_Button.Name = "Clearance_Button"
        Me.Clearance_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Clearance_Button.OnDisabledState.BorderRadius = 1
        Me.Clearance_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Clearance_Button.OnDisabledState.BorderThickness = 1
        Me.Clearance_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Clearance_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Clearance_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Clearance_Button.OnDisabledState.IconRightImage = Nothing
        Me.Clearance_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Clearance_Button.onHoverState.BorderRadius = 1
        Me.Clearance_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Clearance_Button.onHoverState.BorderThickness = 1
        Me.Clearance_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Clearance_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Clearance_Button.onHoverState.IconLeftImage = Nothing
        Me.Clearance_Button.onHoverState.IconRightImage = Nothing
        Me.Clearance_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Clearance_Button.OnIdleState.BorderRadius = 1
        Me.Clearance_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Clearance_Button.OnIdleState.BorderThickness = 1
        Me.Clearance_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Clearance_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Clearance_Button.OnIdleState.IconLeftImage = Nothing
        Me.Clearance_Button.OnIdleState.IconRightImage = Nothing
        Me.Clearance_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Clearance_Button.OnPressedState.BorderRadius = 1
        Me.Clearance_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Clearance_Button.OnPressedState.BorderThickness = 1
        Me.Clearance_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Clearance_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Clearance_Button.OnPressedState.IconLeftImage = Nothing
        Me.Clearance_Button.OnPressedState.IconRightImage = Nothing
        Me.Clearance_Button.Size = New System.Drawing.Size(245, 55)
        Me.Clearance_Button.TabIndex = 4
        Me.Clearance_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Clearance_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Clearance_Button.TextMarginLeft = 0
        Me.Clearance_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Clearance_Button.UseDefaultRadiusAndThickness = True
        '
        'Record_Button
        '
        Me.Record_Button.AllowAnimations = True
        Me.Record_Button.AllowMouseEffects = True
        Me.Record_Button.AllowToggling = False
        Me.Record_Button.AnimationSpeed = 200
        Me.Record_Button.AutoGenerateColors = False
        Me.Record_Button.AutoRoundBorders = False
        Me.Record_Button.AutoSizeLeftIcon = True
        Me.Record_Button.AutoSizeRightIcon = True
        Me.Record_Button.BackColor = System.Drawing.Color.Transparent
        Me.Record_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Record_Button.BackgroundImage = CType(resources.GetObject("Record_Button.BackgroundImage"), System.Drawing.Image)
        Me.Record_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Record_Button.ButtonText = "RECORD"
        Me.Record_Button.ButtonTextMarginLeft = 0
        Me.Record_Button.ColorContrastOnClick = 45
        Me.Record_Button.ColorContrastOnHover = 45
        Me.Record_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges10.BottomLeft = True
        BorderEdges10.BottomRight = True
        BorderEdges10.TopLeft = True
        BorderEdges10.TopRight = True
        Me.Record_Button.CustomizableEdges = BorderEdges10
        Me.Record_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Record_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Record_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Record_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Record_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Record_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Record_Button.ForeColor = System.Drawing.Color.White
        Me.Record_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Record_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Record_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Record_Button.IconMarginLeft = 11
        Me.Record_Button.IconPadding = 10
        Me.Record_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Record_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Record_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Record_Button.IconSize = 25
        Me.Record_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Record_Button.IdleBorderRadius = 1
        Me.Record_Button.IdleBorderThickness = 1
        Me.Record_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Record_Button.IdleIconLeftImage = Nothing
        Me.Record_Button.IdleIconRightImage = Nothing
        Me.Record_Button.IndicateFocus = False
        Me.Record_Button.Location = New System.Drawing.Point(0, 409)
        Me.Record_Button.Name = "Record_Button"
        Me.Record_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Record_Button.OnDisabledState.BorderRadius = 1
        Me.Record_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Record_Button.OnDisabledState.BorderThickness = 1
        Me.Record_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Record_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Record_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Record_Button.OnDisabledState.IconRightImage = Nothing
        Me.Record_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Record_Button.onHoverState.BorderRadius = 1
        Me.Record_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Record_Button.onHoverState.BorderThickness = 1
        Me.Record_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Record_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Record_Button.onHoverState.IconLeftImage = Nothing
        Me.Record_Button.onHoverState.IconRightImage = Nothing
        Me.Record_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Record_Button.OnIdleState.BorderRadius = 1
        Me.Record_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Record_Button.OnIdleState.BorderThickness = 1
        Me.Record_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Record_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Record_Button.OnIdleState.IconLeftImage = Nothing
        Me.Record_Button.OnIdleState.IconRightImage = Nothing
        Me.Record_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Record_Button.OnPressedState.BorderRadius = 1
        Me.Record_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Record_Button.OnPressedState.BorderThickness = 1
        Me.Record_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Record_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Record_Button.OnPressedState.IconLeftImage = Nothing
        Me.Record_Button.OnPressedState.IconRightImage = Nothing
        Me.Record_Button.Size = New System.Drawing.Size(245, 55)
        Me.Record_Button.TabIndex = 7
        Me.Record_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Record_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Record_Button.TextMarginLeft = 0
        Me.Record_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Record_Button.UseDefaultRadiusAndThickness = True
        '
        'Blotter_Button
        '
        Me.Blotter_Button.AllowAnimations = True
        Me.Blotter_Button.AllowMouseEffects = True
        Me.Blotter_Button.AllowToggling = False
        Me.Blotter_Button.AnimationSpeed = 200
        Me.Blotter_Button.AutoGenerateColors = False
        Me.Blotter_Button.AutoRoundBorders = False
        Me.Blotter_Button.AutoSizeLeftIcon = True
        Me.Blotter_Button.AutoSizeRightIcon = True
        Me.Blotter_Button.BackColor = System.Drawing.Color.Transparent
        Me.Blotter_Button.BackColor1 = System.Drawing.Color.DodgerBlue
        Me.Blotter_Button.BackgroundImage = CType(resources.GetObject("Blotter_Button.BackgroundImage"), System.Drawing.Image)
        Me.Blotter_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Blotter_Button.ButtonText = "BLOTTER"
        Me.Blotter_Button.ButtonTextMarginLeft = 0
        Me.Blotter_Button.ColorContrastOnClick = 45
        Me.Blotter_Button.ColorContrastOnHover = 45
        Me.Blotter_Button.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges11.BottomLeft = True
        BorderEdges11.BottomRight = True
        BorderEdges11.TopLeft = True
        BorderEdges11.TopRight = True
        Me.Blotter_Button.CustomizableEdges = BorderEdges11
        Me.Blotter_Button.DialogResult = System.Windows.Forms.DialogResult.None
        Me.Blotter_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Blotter_Button.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Blotter_Button.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Blotter_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.Blotter_Button.Font = New System.Drawing.Font("Segoe UI", 9.0!)
        Me.Blotter_Button.ForeColor = System.Drawing.Color.White
        Me.Blotter_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.Blotter_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.Blotter_Button.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.Blotter_Button.IconMarginLeft = 11
        Me.Blotter_Button.IconPadding = 10
        Me.Blotter_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.Blotter_Button.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.Blotter_Button.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.Blotter_Button.IconSize = 25
        Me.Blotter_Button.IdleBorderColor = System.Drawing.Color.DodgerBlue
        Me.Blotter_Button.IdleBorderRadius = 1
        Me.Blotter_Button.IdleBorderThickness = 1
        Me.Blotter_Button.IdleFillColor = System.Drawing.Color.DodgerBlue
        Me.Blotter_Button.IdleIconLeftImage = Nothing
        Me.Blotter_Button.IdleIconRightImage = Nothing
        Me.Blotter_Button.IndicateFocus = False
        Me.Blotter_Button.Location = New System.Drawing.Point(0, 349)
        Me.Blotter_Button.Name = "Blotter_Button"
        Me.Blotter_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.Blotter_Button.OnDisabledState.BorderRadius = 1
        Me.Blotter_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Blotter_Button.OnDisabledState.BorderThickness = 1
        Me.Blotter_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.Blotter_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.Blotter_Button.OnDisabledState.IconLeftImage = Nothing
        Me.Blotter_Button.OnDisabledState.IconRightImage = Nothing
        Me.Blotter_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Blotter_Button.onHoverState.BorderRadius = 1
        Me.Blotter_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Blotter_Button.onHoverState.BorderThickness = 1
        Me.Blotter_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.Blotter_Button.onHoverState.ForeColor = System.Drawing.Color.White
        Me.Blotter_Button.onHoverState.IconLeftImage = Nothing
        Me.Blotter_Button.onHoverState.IconRightImage = Nothing
        Me.Blotter_Button.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue
        Me.Blotter_Button.OnIdleState.BorderRadius = 1
        Me.Blotter_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Blotter_Button.OnIdleState.BorderThickness = 1
        Me.Blotter_Button.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue
        Me.Blotter_Button.OnIdleState.ForeColor = System.Drawing.Color.White
        Me.Blotter_Button.OnIdleState.IconLeftImage = Nothing
        Me.Blotter_Button.OnIdleState.IconRightImage = Nothing
        Me.Blotter_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Blotter_Button.OnPressedState.BorderRadius = 1
        Me.Blotter_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.Blotter_Button.OnPressedState.BorderThickness = 1
        Me.Blotter_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.Blotter_Button.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.Blotter_Button.OnPressedState.IconLeftImage = Nothing
        Me.Blotter_Button.OnPressedState.IconRightImage = Nothing
        Me.Blotter_Button.Size = New System.Drawing.Size(245, 55)
        Me.Blotter_Button.TabIndex = 6
        Me.Blotter_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.Blotter_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.Blotter_Button.TextMarginLeft = 0
        Me.Blotter_Button.TextPadding = New System.Windows.Forms.Padding(0)
        Me.Blotter_Button.UseDefaultRadiusAndThickness = True
        '
        'MainPanel
        '
        Me.MainPanel.BackgroundColor = System.Drawing.Color.Transparent
        Me.MainPanel.BackgroundImage = CType(resources.GetObject("MainPanel.BackgroundImage"), System.Drawing.Image)
        Me.MainPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch
        Me.MainPanel.BorderColor = System.Drawing.Color.Transparent
        Me.MainPanel.BorderRadius = 3
        Me.MainPanel.BorderThickness = 1
        Me.MainPanel.Location = New System.Drawing.Point(243, -1)
        Me.MainPanel.Name = "MainPanel"
        Me.MainPanel.ShowBorders = True
        Me.MainPanel.Size = New System.Drawing.Size(1108, 728)
        Me.MainPanel.TabIndex = 1
        '
        'MainForm
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(1346, 725)
        Me.Controls.Add(Me.MainPanel)
        Me.Controls.Add(Me.BunifuPanel1)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D
        Me.Name = "MainForm"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Form1"
        Me.BunifuPanel1.ResumeLayout(False)
        Me.BunifuPanel1.PerformLayout()
        Me.ResumeLayout(False)

    End Sub

    Friend WithEvents BunifuPanel1 As Bunifu.UI.WinForms.BunifuPanel
    Friend WithEvents Dashboard_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents BunifuLabel1 As Bunifu.UI.WinForms.BunifuLabel
    Friend WithEvents Residents_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents Purok_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents Clearance_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents Officials_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents Blotter_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents Record_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents Logout_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents Activities_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents Settings_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents Archive_Button As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents MainPanel As Bunifu.UI.WinForms.BunifuPanel
End Class
